Feature/event card
dev-pira/site pull request #34
Opened 2022-09-10 01:14 UTC by murilobeltrame

closes #9

2022-09-15 12:07 UTC, gabrielcesar95 commented on components/EventCard/EventCard.tsx
> +        formatedDateTime += ` às ${dateTime.getHours()}h${dateTime.getMinutes().toString().padStart(2, '0')}`
```typescript
if (dateTime.getHours() && dateTime.getMinutes()) {
         formatedDateTime += ` às ${dateTime.getHours().toString().padStart(2, '0')}h${dateTime.getMinutes().toString().padStart(2, '0')}`
```

2022-09-15 12:11 UTC, gabrielcesar95 requested changes
só adicionar um padStart()

2022-09-15 22:46 UTC, murilobeltrame commented on components/EventCard/EventCard.tsx
> +        formatedDateTime += ` às ${dateTime.getHours()}h${dateTime.getMinutes().toString().padStart(2, '0')}`
Fala man. Nesse caso, eu usei || porque 0 é considerado um valor falsy.
Desse modo, se getHours() OU getMinutes() tiverem valor diferente de 0 a formatação de data && horário do evento prosseguiria.

2022-09-17 12:58 UTC, KaiqueMS2019 approved these changes

2022-09-17 13:03 UTC, merged