Feature/pagina detalhes evento
dev-pira/site pull request #35
Opened 2022-09-14 02:30 UTC by murilobeltrame

Closes #28

2022-09-14 23:18 UTC, gabrielcesar95 commented on components/EventDetailContent/EventDetailContent.tsx
> +                                        <Box key={talk.title} sx={{background: 'white', borderRadius: '10px'}}>
creio que seria mais interessante setar as keys como o índice dessa `talk`. Por mais que seja altamente improvável, a string `talk.title` ainda tem uma possibilidade de se repetir.

para tal, seria só setar
linha 22:
`{tracks.map((track, index) => {`

linha 29:
`<Box key={index} sx={{background: 'white', borderRadius: '10px'}}>`

2022-09-15 00:03 UTC, murilobeltrame commented on components/EventDetailContent/EventDetailContent.tsx
> +                                        <Box key={talk.title} sx={{background: 'white', borderRadius: '10px'}}>
Atualizado! Tkx

2022-09-15 11:53 UTC, gabrielcesar95 commented on components/EventDetailInfo/EventDetailInfo.tsx
> +        formatedDateTime += ` às ${dateTime.getHours()}h${dateTime.getMinutes().toString().padStart(2, '0')}`
```typescript
if (dateTime.getHours() && dateTime.getMinutes()) {
         formatedDateTime += ` às ${dateTime.getHours().toString().padStart(2, '0')}h${dateTime.getMinutes().toString().padStart(2, '0')}`
```

2022-09-15 12:00 UTC, gabrielcesar95 commented on components/EventPartners/EventPartners.tsx
> +            {partners.map((key) => {
essa variável `key` está meio vaga. Não seria melhor mapear como `...map(name, index)` e passar o index para a prop key da linha 15?

2022-09-15 12:03 UTC, gabrielcesar95 commented on pages/event-details.tsx
> +        dateTime: new Date(),
setar `new Date()` pode criar um bug em que a data exibida seja sempre a data atual. Eu preferiria setar esse valor como `null`

2022-09-15 12:10 UTC, gabrielcesar95 requested changes
só adicionar um padStart() e um bug em potencial que acho melhor elimarmos logo

2022-09-15 22:37 UTC, murilobeltrame commented on components/EventDetailInfo/EventDetailInfo.tsx
> +        formatedDateTime += ` às ${dateTime.getHours()}h${dateTime.getMinutes().toString().padStart(2, '0')}`
Fala man. Nesse caso, eu usei `||` porque 0 é considerado um valor _falsy_.
Desse modo, se `getHours()` OU `getMinutes()` tiverem valor diferente de 0 a formatação de data && horário do evento prosseguiria.

2022-09-15 22:39 UTC, murilobeltrame commented on pages/event-details.tsx
> +        dateTime: new Date(),
Oi man. Esse é apenas um caso de exemplo, por isso mantive `new Date()`.
Nas páginas de detalhes de evento esse objeto todo deveria ser preenchido com dados reais.
É o "lorem ipsum" de data =)

2022-09-15 22:43 UTC, murilobeltrame reviewed
Atualizando componente de parceiros de eventos para suportar índice e num nomenclatura mais clara

2022-09-19 12:07 UTC, gabrielcesar95 commented on components/EventDetailInfo/EventDetailInfo.tsx
> +        formatedDateTime += ` às ${dateTime.getHours()}h${dateTime.getMinutes().toString().padStart(2, '0')}`
Saquei. Eu tava pensando no cenário de ser uma hora redonda, tipo _00:00_ ou _15:00_. Creio que nesse caso faça sentido ter o `||` mesmo...

Mas não seria interessante setar o dateTime como nullable na linha 5, e simplificar esse if?
Digo pq pra mim faria sentido um evento não ter uma data, enquanto a grade ainda não tá fechada, e se existe um `Date()` no `dateTime` ele sempre terá horas e minutos válidos.

2022-09-19 23:07 UTC, gabrielcesar95 approved these changes

2022-09-19 23:52 UTC, murilobeltrame commented on components/EventDetailInfo/EventDetailInfo.tsx
> +        formatedDateTime += ` às ${dateTime.getHours()}h${dateTime.getMinutes().toString().padStart(2, '0')}`
Como falamos na paralela. Ideia é que a data seja obrigatória, mas não o horário ;)

2022-09-19 23:52 UTC, murilobeltrame commented on components/EventPartners/EventPartners.tsx
> +            {partners.map((key) => {
Atualizado man.

2022-09-23 01:55 UTC, merged